web:
  build: .
  environment:
  volumes:
    - ./app:/srv/app
    - ./src:/srv/src
    - ./vendor:/srv/vendor
    - ./web:/srv/web
  ports:
   - "3000:3000"
  links:
   - rethinkdb
rethinkdb:
  image: rethinkdb
  ports:
  - "28015:28015"